server:
  port: 9937

spring:
  application:
    name: mmhsy-promotion-api
  sleuth:
    sampler:
      percentage: 1.0
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.133:3306/mmhsy_promotion?useUnicode=true&character_set_server=utf8mb4&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: 123456Aa
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 8
      max-wait: 60000
      use-unfair-lock: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: wall

#mybatis相关配置#
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.mmhsy.*.*.entity.*.domain,com.mmhsy.*.*.entity.*.*.domain

mapper:
  mappers:
    - com.mmhsy.base.mapper.BaseMapper

swagger:
  enable: true
  base-package: com.mmhsy
  contact:
    name: 妈妈好生意
    url:
    email: xxx@xxx.com
  title: 促销配置服务
  description: 促销配置服务
  version: 1.0.0
  resources:
    - {name: "促销配置服务(API)", location: "/v2/api-docs"}

threadPool:
  coreSize: 20
  maxCoreSize: 100
  queueSize: 1000
  keepAlive: 1

ribbon:
  ReadTimeout: 30000
  SocketTimeout: 30000